### ISSUE TITLE
Problems data logging

### ISSUE THREAD

**Issue by naricdurmus** [JoshuaJB/pebble-accel-log#5]
Dear Joshua,

We have tried logging accelerometer data for a longer time. Our goal is to log for 24 hours. However the first measurement gave the following error after 8 minutes: 'It seems like a data buffer is out of sync. Data will be corrupted. Please flush buffers and try again.' The second measurement did continue but the Android app displayed a negative time. When we checked the data we saw the following time values over sample numbers, see Plot_Time-sample. 
![plot_time-samples dominant_wrist 11 mrt 2016 100533](https://cloud.githubusercontent.com/assets/17780572/13698481/a1e7effc-e774-11e5-8b4a-c7e1b2b0abba.png)
.  Although we expected a linear line, as time increases with a fixed step. 
Do you know how to solve these problems and is it possible to measure for 24 hours?

Also we wondered if it is possible to require to press the stop button for a longer time to stop the measurement, to prevent it to be stopped accidentally?

Greetings from the Netherlands!

**Comment by JoshuaJB** [comment]
Thanks for the bug report! I was unable to reproduce the erratic timestamp issue, but noticed several issues with the backing code. I reworked it significantly in dfe8ef4 and ran several tests ranging from a few seconds to 48 minutes without encountering the negative timestamp issue.

Could you try again with the latest code? It's a good bit more robust. If it happens again, if possible, please include the number of samples and seconds. That should make it easier for me to reproduce any problems that you're having.

To answer your other questions; the system was originally designed with the intent to work for over 24 hours, but that's never been tested. A quick calculation shows that it should be able to run offline for up to 2 days in the current configuration and basically forever if left connected to the phone.

Tweaking stop button configuration should be trivial. Are you referring to the one on the watch or the one in the app?

**Comment by naricdurmus** [comment]
Thanks Joshua for the help! The code works now. 

But if we want to measure for a longer time period (several minutes), we get the following error on the phone:_ 'It seems like a data buffer is out of sync. Data will be corrupted. Please flush buffers and try again.' _ Do you know what causes this error?

Another error occurred on a different smartwatch and phone combination, the smartwatch displayed after several minutes: _'Someone else is writing to this logging session.' _ Afterwards, the phone application restarted itself (while receiving the data from the Pebble) and no data was saved.

To answer your question in the previous post: we were referring to the stop button on the watch to make it less likely to stop the measurement accidentally. 

We hope you will be able to solve this issue, if you have any further questions, please contact us.

**Comment by JoshuaJB** [comment]
Nariç, thanks again for the bug report! I am glad to hear that that specific issue is fixed! For the other problems that you mentioned, I have created issues #6, #7, and #8.
